language: csharp
mono: none
dotnet: 3.1.100
script:
- dotnet restore
- dotnet build ./Nayu/
deploy:
  provider: heroku
  api_key:
    secure: dZj92HpdRsmyM2xkIV+8ggtDtJOXcX5qDepCRYf76y9/dWbCfh7jKSw7Wg6h+zFFfVuJTwyj320u3qnkRsQfalJz0f9HVbQ30LZ9pT5JayK78rbipD6C3rPp7eADyLKSq5kHOQc5L2XpPZNNIfwnW64UU1P5+dYUWqorr6vxg71kYSxTGqHBuj4N2yad5nVWUZsewTVc7cTQOCsP4NV2jeBAf2b1iz/Vh1tajuoHZmsFaSXAnO3aFOLrvDn7oZ9TglJ1SU9IMg8kGqh1zXfWznp4CvaK2+/VV1Hjlzv5qF6xsfUC3rx8QdEdF1qIS4EvPh2h78dgTZs0e6H3AZN9tnDVwBn7N3U1JrVeDiTfq3/Lj6GJPix/TCtOCz4O5DfOorVWoN4J3wA66V422e4fqDeAdgybkkEqP/sRb8BRJ1VOXm5wT3PKi8QllurzXfNNjswhvIJV8dJVxIQ6DtHtRXqWioc1lhQ3Kdj65ua8+o1pnVL2slxmvtiePP0wnMd93j2wfUoI7Hr88eJnC+Dp0zKWu6BJHIADmkiArB04KvY4SV0IJ8jOlpu5a+lrqqaxkwe8pPOA9Nb9BbNLpjNG9qe815czywvhRSba5HFfZY5zvPaZ+vjJ8ykDFwy9TVw12M8SVkIlXZJ391EgfdLxzf4E7wKD8a/WeS7M44UR/xU=
  app: Nayu
  on:
    repo: Phytal/Nayu
