language: csharp
mono: none
dotnet: 3.1.100
script:
- dotnet restore
- dotnet build ./Nayu/
deploy:
  provider: heroku
  api_key:
    secure: WfEnHWGY1hJ9d6UYrICr/yieLHLmWsXrYvpw3XILh6BRtNCen8QOHOnM3blr7/CyXEfWRXHIEaHQSwh1IpqeIKNuEziVH4UB45p2GfZ2dJaFkYj8988qw5aGb8tdJHhfHskWA4HlQgGg/Qr2UOKvUd7yQ15NfoMNDAClz0E3JYpr8qj2HTIe+DK2bhdrqW7QDyIaX213P7dYrwvE7wxyo1r3hwkM1yiJFuDSiaerRQ+RVgnYOM0T0rojf3mKCvTErg53HrDBwI2nzPnPEOJt2ELsCe8rhGrY1YzuDw5XV6EB6ZrNMzd1XQYzW3WUq3hhE965LaIWrxQ7s/xD+IWtfP327S9+fBFef+KOh0nByhVOMAI66HHXMIVgmDeNfB2CVJDU+8falz+0Id2/+iU4/bopCPeHwI2L3ZXcXNsCyRwLJTsGlMyJ/nIp3hIvUZTOIZtGJ+B8yy6jDXAwXZig48xE7n8QEEgp8pPLY8uuVmRgpGqGI8AXi1NCxExCwRP5X2xOpN08Fg5gSEkKT70GClA/vP4iHmN/FFoN1+mZkMM8qRNGITAxA4J6dk9qP13PSaM6L2Wgrnmsf+tkh3zKmzYQuKfUmdhiJe67onPjOQ/VEhsUM8mk7Z+VwSDFpLvH3xT2BbHohJjS9uVTKTldDoM2dGi1MiZYLPgxjFeoK3s=
  app: Nayu
  on:
    repo: Phytal/Nayu
