language: csharp
mono: none
dotnet: 3.1.100
script:
- dotnet restore
- dotnet build ./Nayu/
deploy:
  provider: heroku
  api_key:
    secure: WY/73wWH1fzG22G4BDr0vYGAWdQ4AsKM02831nmh1ld89Q8UJKUABzyBY4WZl1k5xTeqDxgFrtEic3YvOsZVV29g461cfWMmrgEsvIveaXa84pwe/eE23Fa9WjTk6XsiFQPlL4RvJ4L0Sq0PeRy0qvI/E6DrnyIbKZ8ZjVCKl5ES/pwogCDLtd5allEVG1h7FqLopp9J7LYmzcL2egOUUGIIVrXK+5ezU7lf0CTZJ9uJLVGMaid1E+TiDXaNbxDePIsBYDrAU0y+XlOP0DUocJgSKZAEZEgATYZSMATy3egKNnhU60YvzeqGqxtO79Hqrrw6X9uY+CEVfYsDVMpJlwNyH+MgVMSiWxFvZSMf9aMQR2thjuF6Jcs9GIdfzQW/Zj9kyt1L7SeAfi408SI3yszyajzrjSC8S3WzKvxRx2wlL1B80Xjk4Ae1t+RrERudMCccUEEFrxbkipWRxgNdFZFOzkaVurPxPKp9uEu5KvQyypXEl71rAGRCdD3Iah/WptLMX2iMOS+Sgxoyhsr14/lftXThMXRni0xmjnj970Zk4knldW6l8Q0+FJkT6X5LZNEtNsEW8QjWS4zWlAsjGMMmJiByLmn8eU2UIzassQAovwo8UxIGo5tl3PmLgXEiv/L7jc9xAzhvSRkZKKN8jVp3EDnZbwkVWrEzyeNzHEw=
  app: Nayu
  on:
    repo: Phytal/Nayu
