language: csharp
mono: none
dotnet: 3.1.100
script:
- dotnet restore
- dotnet build ./Nayu/
deploy:
  provider: heroku
  api_key:
    secure: pIup2Eup/mJD516vy3oQZqKRKPiEeXhmalsTGL6Whe16jGql7GQlk8HODAYdsqXtFAObTgaW+KeSqLyJyyR6rIPiqX2gGdEh1VfcQtHdmS81G0ALAK8aJOAXRJqlSO+GnyCBwMOV52kN3Lkk7RWIrtT3UqQ6+XX9t3XsQ1uLKGp0UZES0r4gHFhYlczgYzbdia25G+JnvRaLk8E/nLNeopCW6zex6uuf93QLZLfb54GxkympFW/mxhG3vQ0PuMPJ7ToOPhtAh3LT540t7e+icYbHBTXUuaBxMadRwzqJuMr3VSRj79Y2CINtehJdudTMdH26owDEdfATtl5LNiFUvRMn3hMG4GJz3Jk4kwIUxkvaAYl7A8Djf1NWEHt4x+3ANarLiqdF+zQST4bAZyTLZSXW/DRi9XsDmibvy+G83j96wa4RO91B7V+Hs8dvtqUaXQXGycsUwVPkBakOoxwtCA4o3OziUuBBj70FxoChmq3aE9sBvWYYVQZTx4OrCCesPu9yh/unzmdkjDDPIvpXOr5J7xdMgTpZlO79vxEX8Poa9/9+JedUwGQWkqOWGdVNNGYmwhbt/RcQCbZJRDUfVHG3YprhTgaHj2I2m6lsvjWvsE3RdLRUJ4skqwaSo7Qka7gypvuLS4JKuiljObUb7Y6tU9VYK9zjrSbQmLHmx+8=
  app: nayuu
  on:
    repo: Phytal/Nayu
