version: 1.0.0-{build}
configuration: Release

before_build: 
    - nuget restore

image: Visual Studio 2017

build: 
    verbosity: minimal
    publish_wap: true
    
install:
  - cmd: choco install dotnetcore-sdk --pre